// ======================================================================
// \title  LogSeverityEnumAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for LogSeverity enum
// ======================================================================

#ifndef Fw_LogSeverityEnumAc_HPP
#define Fw_LogSeverityEnumAc_HPP

#include "FpConfig.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Fw {

  //! Enum representing event severity
  class LogSeverity :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The serial representation type
      typedef I32 SerialType;

      //! The raw enum type
      enum T {
        //! A fatal non-recoverable event
        FATAL = 1,
        //! A serious but recoverable event
        WARNING_HI = 2,
        //! A less serious but recoverable event
        WARNING_LO = 3,
        //! An activity related to commanding
        COMMAND = 4,
        //! Important informational events
        ACTIVITY_HI = 5,
        //! Less important informational events
        ACTIVITY_LO = 6,
        //! Software diagnostic events
        DIAGNOSTIC = 7,
      };

      //! For backwards compatibility
      typedef T t;

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE = sizeof(SerialType),
        //! The number of enumerated constants
        NUM_CONSTANTS = 7,
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value of FATAL)
      LogSeverity()
      {
        this->e = FATAL;
      }

      //! Constructor (user-provided value)
      LogSeverity(
          const T e //!< The raw enum value
      )
      {
        this->e = e;
      }

      //! Copy constructor
      LogSeverity(
          const LogSeverity& obj //!< The source object
      )
      {
        this->e = obj.e;
      }

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator (object)
      LogSeverity& operator=(
          const LogSeverity& obj //!< The source object
      );

      //! Copy assignment operator (raw enum)
      LogSeverity& operator=(
          T e //!< The enum value
      );

      //! Conversion operator
      operator T() const
      {
        return this->e;
      }

      //! Equality operator
      bool operator==(T e) const
      {
        return this->e == e;
      }

      //! Inequality operator
      bool operator!=(T e) const
      {
        return !(*this == e);
      }

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const LogSeverity& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Check raw enum value for validity
      bool isValid() const;

      //! Serialize raw enum value to SerialType
      Fw::SerializeStatus serialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialize raw enum value from SerialType
      Fw::SerializeStatus deserialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

      //! Convert enum to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

    public:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The raw enum value
      T e;

  };

}

#endif
