// ======================================================================
// \title  CmdResponseEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for CmdResponse enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Fw/Cmd/CmdResponseEnumAc.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  CmdResponse& CmdResponse ::
    operator=(const CmdResponse& obj)
  {
    this->e = obj.e;
    return *this;
  }

  CmdResponse& CmdResponse ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const CmdResponse& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool CmdResponse ::
    isValid() const
  {
    return ((e >= OK) && (e <= BUSY));
  }

  Fw::SerializeStatus CmdResponse ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus CmdResponse ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void CmdResponse ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OK:
        s = "OK";
        break;
      case INVALID_OPCODE:
        s = "INVALID_OPCODE";
        break;
      case VALIDATION_ERROR:
        s = "VALIDATION_ERROR";
        break;
      case FORMAT_ERROR:
        s = "FORMAT_ERROR";
        break;
      case EXECUTION_ERROR:
        s = "EXECUTION_ERROR";
        break;
      case BUSY:
        s = "BUSY";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
