// ======================================================================
// \title  DirectionEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Direction enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Fw/Types/DirectionEnumAc.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  Direction& Direction ::
    operator=(const Direction& obj)
  {
    this->e = obj.e;
    return *this;
  }

  Direction& Direction ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const Direction& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool Direction ::
    isValid() const
  {
    return ((e >= IN) && (e <= INOUT));
  }

  Fw::SerializeStatus Direction ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus Direction ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void Direction ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case IN:
        s = "IN";
        break;
      case OUT:
        s = "OUT";
        break;
      case INOUT:
        s = "INOUT";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
