// ======================================================================
// \title  PrmGetPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for PrmGet port
// ======================================================================

#ifndef Fw_PrmGetPortAc_HPP
#define Fw_PrmGetPortAc_HPP

#include <cstdio>
#include <cstring>

#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Prm/ParamBuffer.hpp"
#include "Fw/Prm/ParamValidEnumAc.hpp"
#include "Fw/Types/StringType.hpp"

namespace Fw {

  //! Input PrmGet port
  //! Port for getting a parameter
  class InputPrmGetPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          sizeof(FwPrmIdType) +
          Fw::ParamBuffer::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef Fw::ParamValid (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        FwPrmIdType id,
        Fw::ParamBuffer& val
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputPrmGetPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      Fw::ParamValid invoke(
          FwPrmIdType id, //!< Parameter ID
          Fw::ParamBuffer& val //!< Buffer containing serialized parameter value
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output PrmGet port
  //! Port for getting a parameter
  class OutputPrmGetPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputPrmGetPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputPrmGetPort* callPort //!< The input port
      );

      //! Invoke a port interface
      Fw::ParamValid invoke(
          FwPrmIdType id, //!< Parameter ID
          Fw::ParamBuffer& val //!< Buffer containing serialized parameter value
      );

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputPrmGetPort* m_port;

  };

}

#endif
