// ======================================================================
// \title  PrmGetPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PrmGet port
// ======================================================================

#include "F-Prime/Fw/Prm/PrmGetPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputPrmGetPort ::
    InputPrmGetPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputPrmGetPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputPrmGetPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Fw::ParamValid InputPrmGetPort ::
    invoke(
        FwPrmIdType id,
        Fw::ParamBuffer& val
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, id, val);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputPrmGetPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputPrmGetPort ::
    OutputPrmGetPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputPrmGetPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputPrmGetPort ::
    addCallPort(InputPrmGetPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Fw::ParamValid OutputPrmGetPort ::
    invoke(
        FwPrmIdType id,
        Fw::ParamBuffer& val
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(id, val);
  }

}
