// ======================================================================
// \title  PrmSetPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PrmSet port
// ======================================================================

#include "F-Prime/Fw/Prm/PrmSetPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace Fw {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class PrmSetPortBuffer : public Fw::SerializeBufferBase {

      public:

        NATIVE_UINT_TYPE getBuffCapacity() const {
          return InputPrmSetPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputPrmSetPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputPrmSetPort ::
    InputPrmSetPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputPrmSetPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputPrmSetPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputPrmSetPort ::
    invoke(
        FwPrmIdType id,
        Fw::ParamBuffer& val
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, id, val);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputPrmSetPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_SERIALIZATION == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    FwPrmIdType id;
    _status = _buffer.deserialize(id);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    Fw::ParamBuffer val;
    _status = _buffer.deserialize(val);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, id, val);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputPrmSetPort ::
    OutputPrmSetPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputPrmSetPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputPrmSetPort ::
    addCallPort(InputPrmSetPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputPrmSetPort ::
    invoke(
        FwPrmIdType id,
        Fw::ParamBuffer& val
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(id, val);
    }
    else {
      Fw::SerializeStatus _status;
      PrmSetPortBuffer _buffer;

      _status = _buffer.serialize(id);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(val);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(id, val);
#endif
  }

}
